export const clientLogos = [
  'Julius Bär',
  'Microsoft',
  'JLL',
  'Diageo',
  'Nike',
  "Levi's",
  'IBM',
  'J.P. Morgan',
  'General Mills',
  'Heineken',
  'London Stock Exchange',
  'A+E Networks',
  'Standard Chartered',
  'American Express',
  'Baker McKenzie',
  'Haribo',
  'Bosch',
  'BlackRock',
  'Google',
  'Coca-Cola',
  'SABIC',
  'Bank of Singapore',
  'Sports World México',
];
